repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.0
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]

- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.5.5
  hooks:
    # Compile requirements
    - id: pip-compile
      args: [pyproject.toml, -o, requirements.txt]